FROM golang:1.23.7-alpine3.21 AS builder
WORKDIR /app
COPY ../mailstack/. ./mailstack
COPY ../customeros/packages/server/customer-os-neo4j-repository/. ./customer-os-neo4j-repository/
COPY ../customeros/packages/server/customer-os-postgres-repository/. ./customer-os-postgres-repository/

WORKDIR /app/mailstack
RUN go mod tidy
RUN go build -v -o /go/bin/app main.go

# Final stage
FROM alpine:3.14

WORKDIR /app
COPY --from=builder /go/bin/app ./app
COPY --from=builder /app/mailstack/.env ./.env

# Add entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER 65534
ENTRYPOINT ["/entrypoint.sh"]
