FROM golang:1.23.7-alpine3.21 AS builder
WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -v -o /go/bin/app main.go

# Final stage
FROM alpine:3.14

WORKDIR /app
COPY --from=builder /go/bin/app ./app
COPY --from=builder /app/.env ./.env

# Add entrypoint script
COPY deployments/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER 65534
ENTRYPOINT ["/entrypoint.sh"]
