# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/packages/server/mailstack"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "go"
      - "dependencies"
      - "app/mailstack"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
