package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"errors"

	api_errors "github.com/customeros/mailstack/api/errors"
	"github.com/customeros/mailstack/api/graphql/graphql_model"
	"github.com/customeros/mailstack/api/graphql/mappers"
	"github.com/customeros/mailstack/internal/enum"
	"github.com/customeros/mailstack/internal/models"
	"github.com/customeros/mailstack/internal/telemetry"
	"github.com/customeros/mailstack/internal/utils"
)

// SendEmail is the resolver for the sendEmail field.
func (r *mutationResolver) SendEmail(ctx context.Context, input graphql_model.EmailInput) (*graphql_model.EmailResult, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "queryResolver.SendEmail")
	defer spans.Finish()

	tenant := utils.GetTenantFromContext(ctx)
	if tenant == "" {
		spans.TraceError(errors.New("tenant not set"))
		return nil, api_errors.NewError("tenant not set", api_errors.CodeBadInput, nil)
	}
	userId := utils.GetUserIdFromContext(ctx)
	if userId == "" {
		spans.TraceError(errors.New("userId not set"))
		return nil, api_errors.NewError("usedId not set", api_errors.CodeBadInput, nil)
	}

	var result graphql_model.EmailResult
	// TODO FIX
	emailID, emailStatus, err := r.services.EmailService.ScheduleSend(ctx, &models.EmailLog{}, input.AttachmentIds)
	if err != nil {
		spans.TraceError(err)
		errStr := err.Error()
		result.Status = enum.EmailStatusFailed
		result.Error = &errStr
		return &result, err
	}

	result.EmailID = emailID
	result.Status = emailStatus

	return &result, nil
}

// GetAllEmailsInThread is the resolver for the getAllEmailsInThread field.
func (r *queryResolver) GetAllEmailsInThread(ctx context.Context, threadID string) ([]*graphql_model.EmailMessage, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "queryResolver.GetEmailsByThread")
	defer spans.Finish()

	emails, err := r.repositories.EmailRepository.ListByThread(ctx, threadID)
	if err != nil {
		spans.TraceError(err)
		return nil, api_errors.NewError("error getting email thread", api_errors.CodeInternal, nil)
	}
	if emails == nil {
		return nil, api_errors.NewError("thread not found", api_errors.CodeNotFound, nil)
	}

	messages := make([]*graphql_model.EmailMessage, 0, len(emails))
	for _, email := range emails {
		message := mappers.MapGormEmailToGraph(email)
		attachments, err := r.repositories.EmailAttachmentRepository.ListByEmail(ctx, email.ID)
		if err != nil {
			spans.TraceError(err)
			return nil, api_errors.NewError("error getting attachment count", api_errors.CodeInternal, nil)
		}
		message.AttachmentCount = len(attachments)
		messages = append(messages, message)
	}

	return messages, nil
}

// GetThreadMetadata is the resolver for the getThreadMetadata field.
func (r *queryResolver) GetThreadMetadata(ctx context.Context, threadID string) (*graphql_model.ThreadMetadata, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "queryResolver.GetThreadMetadata")
	defer spans.Finish()

	threadRecord, err := r.repositories.EmailThreadRepository.GetByID(ctx, threadID)
	if err != nil {
		spans.TraceError(err)
		return nil, api_errors.NewError("error getting email thread", api_errors.CodeInternal, nil)
	}
	if threadRecord == nil {
		return nil, api_errors.NewError("thread not found", api_errors.CodeNotFound, nil)
	}

	attachments, err := r.repositories.EmailAttachmentRepository.ListByThread(ctx, threadRecord.ID)
	if err != nil {
		spans.TraceError(err)
		return nil, api_errors.NewError("error getting email attachments", api_errors.CodeInternal, nil)
	}

	threadMetadata := &graphql_model.ThreadMetadata{
		ID: threadID,
		// TODO implement email thread summary
		Summary:        "This is a test email thread about testing",
		Participants:   threadRecord.Participants,
		HasAttachments: threadRecord.HasAttachments,
	}

	if attachments == nil || len(attachments) == 0 {
		return threadMetadata, nil
	}

	files := make([]*graphql_model.Attachment, 0, len(attachments))
	for _, attachment := range attachments {
		files = append(files, mappers.MapGormAttachmentToGraph(attachment))
	}

	threadMetadata.Attachments = files

	return threadMetadata, nil
}
