package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"errors"
	"fmt"

	api_errors "github.com/customeros/mailstack/api/errors"
	"github.com/customeros/mailstack/api/graphql/graphql_model"
	"github.com/customeros/mailstack/api/graphql/mappers"
	internalerrors "github.com/customeros/mailstack/internal/errors"
	"github.com/customeros/mailstack/internal/telemetry"
	"github.com/customeros/mailstack/internal/utils"
)

// AddMailbox is the resolver for the addMailbox field.
func (r *mutationResolver) AddMailbox(ctx context.Context, input graphql_model.MailboxInput) (*graphql_model.Mailbox, error) {
	spans, ctx := telemetry.StartGraphQLSpan(ctx, "mutationResolver.AddMailbox")
	defer spans.Finish()

	tenant := utils.GetTenantFromContext(ctx)
	if tenant == "" {
		spans.TraceError(errors.New("tenant not set"))
		return nil, api_errors.NewError("tenant not set", api_errors.CodeBadInput, nil)
	}
	userId := utils.GetUserIdFromContext(ctx)
	if userId == "" {
		spans.TraceError(errors.New("userId not set"))
		return nil, api_errors.NewError("usedId not set", api_errors.CodeBadInput, nil)
	}

	mailbox, err := r.services.MailboxService.EnrollMailbox(ctx, mappers.MapGraphMailboxInputToGorm(&input))
	if err != nil || mailbox == nil {
		spans.TraceError(err)

		switch err {
		case internalerrors.ErrMailboxExists:
			return nil, api_errors.NewError("unable to add mailbox", api_errors.CodeExists, nil)
		default:
			return nil, api_errors.NewError("unable to add mailbox", api_errors.CodeInternal, nil)

		}
	}

	return mappers.MapGormMailboxToGraph(mailbox), nil
}

// UpdateMailbox is the resolver for the updateMailbox field.
func (r *mutationResolver) UpdateMailbox(ctx context.Context, id string, input graphql_model.MailboxInput) (*graphql_model.Mailbox, error) {
	panic(fmt.Errorf("not implemented: UpdateMailbox - updateMailbox"))
}
