package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"

	"github.com/customeros/mailstack/api/graphql/graphql_model"
)

// GetThreadsByUser is the resolver for the getThreadsByUser field.
func (r *queryResolver) GetThreadsByUser(ctx context.Context, userID string) ([]*graphql_model.EmailThread, error) {
	panic(fmt.Errorf("not implemented: GetThreadsByUser - getThreadsByUser"))
}
