// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/attachment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for attachment processing
type ProcessAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Attachments   []*AttachmentMetadata  `protobuf:"bytes,2,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAttachmentRequest) Reset() {
	*x = ProcessAttachmentRequest{}
	mi := &file_schema_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAttachmentRequest) ProtoMessage() {}

func (x *ProcessAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAttachmentRequest.ProtoReflect.Descriptor instead.
func (*ProcessAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_schema_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessAttachmentRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *ProcessAttachmentRequest) GetAttachments() []*AttachmentMetadata {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Response message for attachment processing
type ProcessAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	HasAttachment bool                   `protobuf:"varint,2,opt,name=has_attachment,json=hasAttachment,proto3" json:"has_attachment,omitempty"`
	AttachmentIds []string               `protobuf:"bytes,3,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAttachmentResponse) Reset() {
	*x = ProcessAttachmentResponse{}
	mi := &file_schema_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAttachmentResponse) ProtoMessage() {}

func (x *ProcessAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAttachmentResponse.ProtoReflect.Descriptor instead.
func (*ProcessAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_schema_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessAttachmentResponse) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *ProcessAttachmentResponse) GetHasAttachment() bool {
	if x != nil {
		return x.HasAttachment
	}
	return false
}

func (x *ProcessAttachmentResponse) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *ProcessAttachmentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Metadata for an email attachment
type AttachmentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentId     string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsInline      bool                   `protobuf:"varint,5,opt,name=is_inline,json=isInline,proto3" json:"is_inline,omitempty"`
	StorageKey    string                 `protobuf:"bytes,6,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	ObjectInfo    string                 `protobuf:"bytes,7,opt,name=object_info,json=objectInfo,proto3" json:"object_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentMetadata) Reset() {
	*x = AttachmentMetadata{}
	mi := &file_schema_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentMetadata) ProtoMessage() {}

func (x *AttachmentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_schema_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentMetadata.ProtoReflect.Descriptor instead.
func (*AttachmentMetadata) Descriptor() ([]byte, []int) {
	return file_schema_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *AttachmentMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AttachmentMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentMetadata) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AttachmentMetadata) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachmentMetadata) GetIsInline() bool {
	if x != nil {
		return x.IsInline
	}
	return false
}

func (x *AttachmentMetadata) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *AttachmentMetadata) GetObjectInfo() string {
	if x != nil {
		return x.ObjectInfo
	}
	return ""
}

var File_schema_attachment_proto protoreflect.FileDescriptor

const file_schema_attachment_proto_rawDesc = "" +
	"\n" +
	"\x17schema/attachment.proto\x12\tmailstack\"v\n" +
	"\x18ProcessAttachmentRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12?\n" +
	"\vattachments\x18\x02 \x03(\v2\x1d.mailstack.AttachmentMetadataR\vattachments\"\xa9\x01\n" +
	"\x19ProcessAttachmentResponse\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12%\n" +
	"\x0ehas_attachment\x18\x02 \x01(\bR\rhasAttachment\x12%\n" +
	"\x0eattachment_ids\x18\x03 \x03(\tR\rattachmentIds\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xe5\x01\n" +
	"\x12AttachmentMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x1b\n" +
	"\tis_inline\x18\x05 \x01(\bR\bisInline\x12\x1f\n" +
	"\vstorage_key\x18\x06 \x01(\tR\n" +
	"storageKey\x12\x1f\n" +
	"\vobject_info\x18\a \x01(\tR\n" +
	"objectInfoB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_attachment_proto_rawDescOnce sync.Once
	file_schema_attachment_proto_rawDescData []byte
)

func file_schema_attachment_proto_rawDescGZIP() []byte {
	file_schema_attachment_proto_rawDescOnce.Do(func() {
		file_schema_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_attachment_proto_rawDesc), len(file_schema_attachment_proto_rawDesc)))
	})
	return file_schema_attachment_proto_rawDescData
}

var file_schema_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_attachment_proto_goTypes = []any{
	(*ProcessAttachmentRequest)(nil),  // 0: mailstack.ProcessAttachmentRequest
	(*ProcessAttachmentResponse)(nil), // 1: mailstack.ProcessAttachmentResponse
	(*AttachmentMetadata)(nil),        // 2: mailstack.AttachmentMetadata
}
var file_schema_attachment_proto_depIdxs = []int32{
	2, // 0: mailstack.ProcessAttachmentRequest.attachments:type_name -> mailstack.AttachmentMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_attachment_proto_init() }
func file_schema_attachment_proto_init() {
	if File_schema_attachment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_attachment_proto_rawDesc), len(file_schema_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_attachment_proto_goTypes,
		DependencyIndexes: file_schema_attachment_proto_depIdxs,
		MessageInfos:      file_schema_attachment_proto_msgTypes,
	}.Build()
	File_schema_attachment_proto = out.File
	file_schema_attachment_proto_goTypes = nil
	file_schema_attachment_proto_depIdxs = nil
}
