// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_classification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for email classification
type EmailClassificationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EmailId            string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Subject            string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	From               *EmailAddress          `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                 []*EmailAddress        `protobuf:"bytes,4,rep,name=to,proto3" json:"to,omitempty"`
	Cc                 []*EmailAddress        `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                []*EmailAddress        `protobuf:"bytes,6,rep,name=bcc,proto3" json:"bcc,omitempty"`
	ReplyTo            *EmailAddress          `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	ReturnPath         string                 `protobuf:"bytes,8,opt,name=return_path,json=returnPath,proto3" json:"return_path,omitempty"`
	Unsubscribe        string                 `protobuf:"bytes,9,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
	Precedence         string                 `protobuf:"bytes,10,opt,name=precedence,proto3" json:"precedence,omitempty"`
	Sender             string                 `protobuf:"bytes,11,opt,name=sender,proto3" json:"sender,omitempty"`
	XAutoReply         string                 `protobuf:"bytes,12,opt,name=x_auto_reply,json=xAutoReply,proto3" json:"x_auto_reply,omitempty"`
	XAutoResponse      string                 `protobuf:"bytes,13,opt,name=x_auto_response,json=xAutoResponse,proto3" json:"x_auto_response,omitempty"`
	XLoop              string                 `protobuf:"bytes,14,opt,name=x_loop,json=xLoop,proto3" json:"x_loop,omitempty"`
	XFailedRecipients  string                 `protobuf:"bytes,15,opt,name=x_failed_recipients,json=xFailedRecipients,proto3" json:"x_failed_recipients,omitempty"`
	ContentDescription string                 `protobuf:"bytes,16,opt,name=content_description,json=contentDescription,proto3" json:"content_description,omitempty"`
	FeedbackId         string                 `protobuf:"bytes,17,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	ForwardedFor       string                 `protobuf:"bytes,18,opt,name=forwarded_for,json=forwardedFor,proto3" json:"forwarded_for,omitempty"`
	Dkim               string                 `protobuf:"bytes,19,opt,name=dkim,proto3" json:"dkim,omitempty"`
	Spf                string                 `protobuf:"bytes,20,opt,name=spf,proto3" json:"spf,omitempty"`
	Dmarc              string                 `protobuf:"bytes,21,opt,name=dmarc,proto3" json:"dmarc,omitempty"`
	ListUnsubscribe    string                 `protobuf:"bytes,22,opt,name=list_unsubscribe,json=listUnsubscribe,proto3" json:"list_unsubscribe,omitempty"`
	AutoSubmitted      string                 `protobuf:"bytes,23,opt,name=auto_submitted,json=autoSubmitted,proto3" json:"auto_submitted,omitempty"`
	MailboxId          string                 `protobuf:"bytes,24,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EmailClassificationRequest) Reset() {
	*x = EmailClassificationRequest{}
	mi := &file_schema_email_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailClassificationRequest) ProtoMessage() {}

func (x *EmailClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailClassificationRequest.ProtoReflect.Descriptor instead.
func (*EmailClassificationRequest) Descriptor() ([]byte, []int) {
	return file_schema_email_classification_proto_rawDescGZIP(), []int{0}
}

func (x *EmailClassificationRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *EmailClassificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailClassificationRequest) GetFrom() *EmailAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EmailClassificationRequest) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailClassificationRequest) GetCc() []*EmailAddress {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailClassificationRequest) GetBcc() []*EmailAddress {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *EmailClassificationRequest) GetReplyTo() *EmailAddress {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *EmailClassificationRequest) GetReturnPath() string {
	if x != nil {
		return x.ReturnPath
	}
	return ""
}

func (x *EmailClassificationRequest) GetUnsubscribe() string {
	if x != nil {
		return x.Unsubscribe
	}
	return ""
}

func (x *EmailClassificationRequest) GetPrecedence() string {
	if x != nil {
		return x.Precedence
	}
	return ""
}

func (x *EmailClassificationRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *EmailClassificationRequest) GetXAutoReply() string {
	if x != nil {
		return x.XAutoReply
	}
	return ""
}

func (x *EmailClassificationRequest) GetXAutoResponse() string {
	if x != nil {
		return x.XAutoResponse
	}
	return ""
}

func (x *EmailClassificationRequest) GetXLoop() string {
	if x != nil {
		return x.XLoop
	}
	return ""
}

func (x *EmailClassificationRequest) GetXFailedRecipients() string {
	if x != nil {
		return x.XFailedRecipients
	}
	return ""
}

func (x *EmailClassificationRequest) GetContentDescription() string {
	if x != nil {
		return x.ContentDescription
	}
	return ""
}

func (x *EmailClassificationRequest) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *EmailClassificationRequest) GetForwardedFor() string {
	if x != nil {
		return x.ForwardedFor
	}
	return ""
}

func (x *EmailClassificationRequest) GetDkim() string {
	if x != nil {
		return x.Dkim
	}
	return ""
}

func (x *EmailClassificationRequest) GetSpf() string {
	if x != nil {
		return x.Spf
	}
	return ""
}

func (x *EmailClassificationRequest) GetDmarc() string {
	if x != nil {
		return x.Dmarc
	}
	return ""
}

func (x *EmailClassificationRequest) GetListUnsubscribe() string {
	if x != nil {
		return x.ListUnsubscribe
	}
	return ""
}

func (x *EmailClassificationRequest) GetAutoSubmitted() string {
	if x != nil {
		return x.AutoSubmitted
	}
	return ""
}

func (x *EmailClassificationRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

// Response message for email classification
type EmailClassificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmailId        string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Classification EmailClassification    `protobuf:"varint,2,opt,name=classification,proto3,enum=mailstack.EmailClassification" json:"classification,omitempty"`
	Details        string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmailClassificationResponse) Reset() {
	*x = EmailClassificationResponse{}
	mi := &file_schema_email_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailClassificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailClassificationResponse) ProtoMessage() {}

func (x *EmailClassificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailClassificationResponse.ProtoReflect.Descriptor instead.
func (*EmailClassificationResponse) Descriptor() ([]byte, []int) {
	return file_schema_email_classification_proto_rawDescGZIP(), []int{1}
}

func (x *EmailClassificationResponse) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *EmailClassificationResponse) GetClassification() EmailClassification {
	if x != nil {
		return x.Classification
	}
	return EmailClassification_EMAIL_CLASSIFICATION_UNKNOWN
}

func (x *EmailClassificationResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *EmailClassificationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_schema_email_classification_proto protoreflect.FileDescriptor

const file_schema_email_classification_proto_rawDesc = "" +
	"\n" +
	"!schema/email_classification.proto\x12\tmailstack\x1a\x1aschema/email_address.proto\x1a&schema/email_classification_enum.proto\"\xdf\x06\n" +
	"\x1aEmailClassificationRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12+\n" +
	"\x04from\x18\x03 \x01(\v2\x17.mailstack.EmailAddressR\x04from\x12'\n" +
	"\x02to\x18\x04 \x03(\v2\x17.mailstack.EmailAddressR\x02to\x12'\n" +
	"\x02cc\x18\x05 \x03(\v2\x17.mailstack.EmailAddressR\x02cc\x12)\n" +
	"\x03bcc\x18\x06 \x03(\v2\x17.mailstack.EmailAddressR\x03bcc\x122\n" +
	"\breply_to\x18\a \x01(\v2\x17.mailstack.EmailAddressR\areplyTo\x12\x1f\n" +
	"\vreturn_path\x18\b \x01(\tR\n" +
	"returnPath\x12 \n" +
	"\vunsubscribe\x18\t \x01(\tR\vunsubscribe\x12\x1e\n" +
	"\n" +
	"precedence\x18\n" +
	" \x01(\tR\n" +
	"precedence\x12\x16\n" +
	"\x06sender\x18\v \x01(\tR\x06sender\x12 \n" +
	"\fx_auto_reply\x18\f \x01(\tR\n" +
	"xAutoReply\x12&\n" +
	"\x0fx_auto_response\x18\r \x01(\tR\rxAutoResponse\x12\x15\n" +
	"\x06x_loop\x18\x0e \x01(\tR\x05xLoop\x12.\n" +
	"\x13x_failed_recipients\x18\x0f \x01(\tR\x11xFailedRecipients\x12/\n" +
	"\x13content_description\x18\x10 \x01(\tR\x12contentDescription\x12\x1f\n" +
	"\vfeedback_id\x18\x11 \x01(\tR\n" +
	"feedbackId\x12#\n" +
	"\rforwarded_for\x18\x12 \x01(\tR\fforwardedFor\x12\x12\n" +
	"\x04dkim\x18\x13 \x01(\tR\x04dkim\x12\x10\n" +
	"\x03spf\x18\x14 \x01(\tR\x03spf\x12\x14\n" +
	"\x05dmarc\x18\x15 \x01(\tR\x05dmarc\x12)\n" +
	"\x10list_unsubscribe\x18\x16 \x01(\tR\x0flistUnsubscribe\x12%\n" +
	"\x0eauto_submitted\x18\x17 \x01(\tR\rautoSubmitted\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x18 \x01(\tR\tmailboxId\"\xbf\x01\n" +
	"\x1bEmailClassificationResponse\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12F\n" +
	"\x0eclassification\x18\x02 \x01(\x0e2\x1e.mailstack.EmailClassificationR\x0eclassification\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_classification_proto_rawDescOnce sync.Once
	file_schema_email_classification_proto_rawDescData []byte
)

func file_schema_email_classification_proto_rawDescGZIP() []byte {
	file_schema_email_classification_proto_rawDescOnce.Do(func() {
		file_schema_email_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_classification_proto_rawDesc), len(file_schema_email_classification_proto_rawDesc)))
	})
	return file_schema_email_classification_proto_rawDescData
}

var file_schema_email_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_email_classification_proto_goTypes = []any{
	(*EmailClassificationRequest)(nil),  // 0: mailstack.EmailClassificationRequest
	(*EmailClassificationResponse)(nil), // 1: mailstack.EmailClassificationResponse
	(*EmailAddress)(nil),                // 2: mailstack.EmailAddress
	(EmailClassification)(0),            // 3: mailstack.EmailClassification
}
var file_schema_email_classification_proto_depIdxs = []int32{
	2, // 0: mailstack.EmailClassificationRequest.from:type_name -> mailstack.EmailAddress
	2, // 1: mailstack.EmailClassificationRequest.to:type_name -> mailstack.EmailAddress
	2, // 2: mailstack.EmailClassificationRequest.cc:type_name -> mailstack.EmailAddress
	2, // 3: mailstack.EmailClassificationRequest.bcc:type_name -> mailstack.EmailAddress
	2, // 4: mailstack.EmailClassificationRequest.reply_to:type_name -> mailstack.EmailAddress
	3, // 5: mailstack.EmailClassificationResponse.classification:type_name -> mailstack.EmailClassification
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_schema_email_classification_proto_init() }
func file_schema_email_classification_proto_init() {
	if File_schema_email_classification_proto != nil {
		return
	}
	file_schema_email_address_proto_init()
	file_schema_email_classification_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_classification_proto_rawDesc), len(file_schema_email_classification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_classification_proto_goTypes,
		DependencyIndexes: file_schema_email_classification_proto_depIdxs,
		MessageInfos:      file_schema_email_classification_proto_msgTypes,
	}.Build()
	File_schema_email_classification_proto = out.File
	file_schema_email_classification_proto_goTypes = nil
	file_schema_email_classification_proto_depIdxs = nil
}
