// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Email address structure
type EmailAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_schema_email_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddress.ProtoReflect.Descriptor instead.
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return file_schema_email_address_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailAddress) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailAddress) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EmailAddress) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_schema_email_address_proto protoreflect.FileDescriptor

const file_schema_email_address_proto_rawDesc = "" +
	"\n" +
	"\x1aschema/email_address.proto\x12\tmailstack\"d\n" +
	"\fEmailAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domainB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_address_proto_rawDescOnce sync.Once
	file_schema_email_address_proto_rawDescData []byte
)

func file_schema_email_address_proto_rawDescGZIP() []byte {
	file_schema_email_address_proto_rawDescOnce.Do(func() {
		file_schema_email_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_address_proto_rawDesc), len(file_schema_email_address_proto_rawDesc)))
	})
	return file_schema_email_address_proto_rawDescData
}

var file_schema_email_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_email_address_proto_goTypes = []any{
	(*EmailAddress)(nil), // 0: mailstack.EmailAddress
}
var file_schema_email_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_email_address_proto_init() }
func file_schema_email_address_proto_init() {
	if File_schema_email_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_address_proto_rawDesc), len(file_schema_email_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_address_proto_goTypes,
		DependencyIndexes: file_schema_email_address_proto_depIdxs,
		MessageInfos:      file_schema_email_address_proto_msgTypes,
	}.Build()
	File_schema_email_address_proto = out.File
	file_schema_email_address_proto_goTypes = nil
	file_schema_email_address_proto_depIdxs = nil
}
