// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_threading.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for attaching an email to a thread
type AttachToThreadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmailId         string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	MailboxId       string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Classification  EmailClassification    `protobuf:"varint,3,opt,name=classification,proto3,enum=mailstack.EmailClassification" json:"classification,omitempty"`
	ReplyTo         string                 `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	References      []string               `protobuf:"bytes,5,rep,name=references,proto3" json:"references,omitempty"`
	Subject         string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	AllParticipants []string               `protobuf:"bytes,7,rep,name=all_participants,json=allParticipants,proto3" json:"all_participants,omitempty"`
	EmailSentAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=email_sent_at,json=emailSentAt,proto3" json:"email_sent_at,omitempty"`
	EmailReceivedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=email_received_at,json=emailReceivedAt,proto3" json:"email_received_at,omitempty"`
	MessageId       string                 `protobuf:"bytes,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttachToThreadRequest) Reset() {
	*x = AttachToThreadRequest{}
	mi := &file_schema_email_threading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachToThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachToThreadRequest) ProtoMessage() {}

func (x *AttachToThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_threading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachToThreadRequest.ProtoReflect.Descriptor instead.
func (*AttachToThreadRequest) Descriptor() ([]byte, []int) {
	return file_schema_email_threading_proto_rawDescGZIP(), []int{0}
}

func (x *AttachToThreadRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *AttachToThreadRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *AttachToThreadRequest) GetClassification() EmailClassification {
	if x != nil {
		return x.Classification
	}
	return EmailClassification_EMAIL_CLASSIFICATION_UNKNOWN
}

func (x *AttachToThreadRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *AttachToThreadRequest) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *AttachToThreadRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AttachToThreadRequest) GetAllParticipants() []string {
	if x != nil {
		return x.AllParticipants
	}
	return nil
}

func (x *AttachToThreadRequest) GetEmailSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailSentAt
	}
	return nil
}

func (x *AttachToThreadRequest) GetEmailReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailReceivedAt
	}
	return nil
}

func (x *AttachToThreadRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Response message for thread attachment operation
type AttachToThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachToThreadResponse) Reset() {
	*x = AttachToThreadResponse{}
	mi := &file_schema_email_threading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachToThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachToThreadResponse) ProtoMessage() {}

func (x *AttachToThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_threading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachToThreadResponse.ProtoReflect.Descriptor instead.
func (*AttachToThreadResponse) Descriptor() ([]byte, []int) {
	return file_schema_email_threading_proto_rawDescGZIP(), []int{1}
}

func (x *AttachToThreadResponse) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *AttachToThreadResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AttachToThreadResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *AttachToThreadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_schema_email_threading_proto protoreflect.FileDescriptor

const file_schema_email_threading_proto_rawDesc = "" +
	"\n" +
	"\x1cschema/email_threading.proto\x12\tmailstack\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&schema/email_classification_enum.proto\"\xc0\x03\n" +
	"\x15AttachToThreadRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12F\n" +
	"\x0eclassification\x18\x03 \x01(\x0e2\x1e.mailstack.EmailClassificationR\x0eclassification\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\tR\areplyTo\x12\x1e\n" +
	"\n" +
	"references\x18\x05 \x03(\tR\n" +
	"references\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12)\n" +
	"\x10all_participants\x18\a \x03(\tR\x0fallParticipants\x12>\n" +
	"\remail_sent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vemailSentAt\x12F\n" +
	"\x11email_received_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0femailReceivedAt\x12\x1d\n" +
	"\n" +
	"message_id\x18\n" +
	" \x01(\tR\tmessageId\"\x94\x01\n" +
	"\x16AttachToThreadResponse\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_threading_proto_rawDescOnce sync.Once
	file_schema_email_threading_proto_rawDescData []byte
)

func file_schema_email_threading_proto_rawDescGZIP() []byte {
	file_schema_email_threading_proto_rawDescOnce.Do(func() {
		file_schema_email_threading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_threading_proto_rawDesc), len(file_schema_email_threading_proto_rawDesc)))
	})
	return file_schema_email_threading_proto_rawDescData
}

var file_schema_email_threading_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_email_threading_proto_goTypes = []any{
	(*AttachToThreadRequest)(nil),  // 0: mailstack.AttachToThreadRequest
	(*AttachToThreadResponse)(nil), // 1: mailstack.AttachToThreadResponse
	(EmailClassification)(0),       // 2: mailstack.EmailClassification
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_schema_email_threading_proto_depIdxs = []int32{
	2, // 0: mailstack.AttachToThreadRequest.classification:type_name -> mailstack.EmailClassification
	3, // 1: mailstack.AttachToThreadRequest.email_sent_at:type_name -> google.protobuf.Timestamp
	3, // 2: mailstack.AttachToThreadRequest.email_received_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schema_email_threading_proto_init() }
func file_schema_email_threading_proto_init() {
	if File_schema_email_threading_proto != nil {
		return
	}
	file_schema_email_classification_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_threading_proto_rawDesc), len(file_schema_email_threading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_threading_proto_goTypes,
		DependencyIndexes: file_schema_email_threading_proto_depIdxs,
		MessageInfos:      file_schema_email_threading_proto_msgTypes,
	}.Build()
	File_schema_email_threading_proto = out.File
	file_schema_email_threading_proto_goTypes = nil
	file_schema_email_threading_proto_depIdxs = nil
}
