// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: schema/email_classification.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailClassificationService_ClassifyEmail_FullMethodName = "/mailstack.EmailClassificationService/ClassifyEmail"
)

// EmailClassificationServiceClient is the client API for EmailClassificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type EmailClassificationServiceClient interface {
	ClassifyEmail(ctx context.Context, in *EmailClassificationRequest, opts ...grpc.CallOption) (*EmailClassificationResponse, error)
}

type emailClassificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailClassificationServiceClient(cc grpc.ClientConnInterface) EmailClassificationServiceClient {
	return &emailClassificationServiceClient{cc}
}

func (c *emailClassificationServiceClient) ClassifyEmail(ctx context.Context, in *EmailClassificationRequest, opts ...grpc.CallOption) (*EmailClassificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailClassificationResponse)
	err := c.cc.Invoke(ctx, EmailClassificationService_ClassifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailClassificationServiceServer is the server API for EmailClassificationService service.
// All implementations must embed UnimplementedEmailClassificationServiceServer
// for forward compatibility.
//
// Service definition
type EmailClassificationServiceServer interface {
	ClassifyEmail(context.Context, *EmailClassificationRequest) (*EmailClassificationResponse, error)
	mustEmbedUnimplementedEmailClassificationServiceServer()
}

// UnimplementedEmailClassificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailClassificationServiceServer struct{}

func (UnimplementedEmailClassificationServiceServer) ClassifyEmail(context.Context, *EmailClassificationRequest) (*EmailClassificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyEmail not implemented")
}
func (UnimplementedEmailClassificationServiceServer) mustEmbedUnimplementedEmailClassificationServiceServer() {
}
func (UnimplementedEmailClassificationServiceServer) testEmbeddedByValue() {}

// UnsafeEmailClassificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailClassificationServiceServer will
// result in compilation errors.
type UnsafeEmailClassificationServiceServer interface {
	mustEmbedUnimplementedEmailClassificationServiceServer()
}

func RegisterEmailClassificationServiceServer(s grpc.ServiceRegistrar, srv EmailClassificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailClassificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailClassificationService_ServiceDesc, srv)
}

func _EmailClassificationService_ClassifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailClassificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailClassificationServiceServer).ClassifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailClassificationService_ClassifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailClassificationServiceServer).ClassifyEmail(ctx, req.(*EmailClassificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailClassificationService_ServiceDesc is the grpc.ServiceDesc for EmailClassificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailClassificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailstack.EmailClassificationService",
	HandlerType: (*EmailClassificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyEmail",
			Handler:    _EmailClassificationService_ClassifyEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/email_classification.proto",
}
