// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_classification_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for email classification types
type EmailClassification int32

const (
	EmailClassification_EMAIL_CLASSIFICATION_UNKNOWN EmailClassification = 0
	EmailClassification_EMAIL_AUTORESPONDER          EmailClassification = 1
	EmailClassification_EMAIL_BULK                   EmailClassification = 2
	EmailClassification_EMAIL_INTERNAL               EmailClassification = 3
	EmailClassification_EMAIL_OK                     EmailClassification = 4
	EmailClassification_EMAIL_SENSITIVE              EmailClassification = 5
	EmailClassification_EMAIL_SPAM                   EmailClassification = 6
	EmailClassification_EMAIL_WARMER                 EmailClassification = 7
	EmailClassification_EMAIL_BOUNCE                 EmailClassification = 8
)

// Enum value maps for EmailClassification.
var (
	EmailClassification_name = map[int32]string{
		0: "EMAIL_CLASSIFICATION_UNKNOWN",
		1: "EMAIL_AUTORESPONDER",
		2: "EMAIL_BULK",
		3: "EMAIL_INTERNAL",
		4: "EMAIL_OK",
		5: "EMAIL_SENSITIVE",
		6: "EMAIL_SPAM",
		7: "EMAIL_WARMER",
		8: "EMAIL_BOUNCE",
	}
	EmailClassification_value = map[string]int32{
		"EMAIL_CLASSIFICATION_UNKNOWN": 0,
		"EMAIL_AUTORESPONDER":          1,
		"EMAIL_BULK":                   2,
		"EMAIL_INTERNAL":               3,
		"EMAIL_OK":                     4,
		"EMAIL_SENSITIVE":              5,
		"EMAIL_SPAM":                   6,
		"EMAIL_WARMER":                 7,
		"EMAIL_BOUNCE":                 8,
	}
)

func (x EmailClassification) Enum() *EmailClassification {
	p := new(EmailClassification)
	*p = x
	return p
}

func (x EmailClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_email_classification_enum_proto_enumTypes[0].Descriptor()
}

func (EmailClassification) Type() protoreflect.EnumType {
	return &file_schema_email_classification_enum_proto_enumTypes[0]
}

func (x EmailClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailClassification.Descriptor instead.
func (EmailClassification) EnumDescriptor() ([]byte, []int) {
	return file_schema_email_classification_enum_proto_rawDescGZIP(), []int{0}
}

var File_schema_email_classification_enum_proto protoreflect.FileDescriptor

const file_schema_email_classification_enum_proto_rawDesc = "" +
	"\n" +
	"&schema/email_classification_enum.proto\x12\tmailstack*\xcb\x01\n" +
	"\x13EmailClassification\x12 \n" +
	"\x1cEMAIL_CLASSIFICATION_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13EMAIL_AUTORESPONDER\x10\x01\x12\x0e\n" +
	"\n" +
	"EMAIL_BULK\x10\x02\x12\x12\n" +
	"\x0eEMAIL_INTERNAL\x10\x03\x12\f\n" +
	"\bEMAIL_OK\x10\x04\x12\x13\n" +
	"\x0fEMAIL_SENSITIVE\x10\x05\x12\x0e\n" +
	"\n" +
	"EMAIL_SPAM\x10\x06\x12\x10\n" +
	"\fEMAIL_WARMER\x10\a\x12\x10\n" +
	"\fEMAIL_BOUNCE\x10\bB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_classification_enum_proto_rawDescOnce sync.Once
	file_schema_email_classification_enum_proto_rawDescData []byte
)

func file_schema_email_classification_enum_proto_rawDescGZIP() []byte {
	file_schema_email_classification_enum_proto_rawDescOnce.Do(func() {
		file_schema_email_classification_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_classification_enum_proto_rawDesc), len(file_schema_email_classification_enum_proto_rawDesc)))
	})
	return file_schema_email_classification_enum_proto_rawDescData
}

var file_schema_email_classification_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_email_classification_enum_proto_goTypes = []any{
	(EmailClassification)(0), // 0: mailstack.EmailClassification
}
var file_schema_email_classification_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_email_classification_enum_proto_init() }
func file_schema_email_classification_enum_proto_init() {
	if File_schema_email_classification_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_classification_enum_proto_rawDesc), len(file_schema_email_classification_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_classification_enum_proto_goTypes,
		DependencyIndexes: file_schema_email_classification_enum_proto_depIdxs,
		EnumInfos:         file_schema_email_classification_enum_proto_enumTypes,
	}.Build()
	File_schema_email_classification_enum_proto = out.File
	file_schema_email_classification_enum_proto_goTypes = nil
	file_schema_email_classification_enum_proto_depIdxs = nil
}
