// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_received_imap.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for an email received via IMAP
type EmailReceivedIMAP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialSync   bool                   `protobuf:"varint,1,opt,name=initial_sync,json=initialSync,proto3" json:"initial_sync,omitempty"`
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Folder        string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	ImapUid       uint32                 `protobuf:"varint,4,opt,name=imap_uid,json=imapUid,proto3" json:"imap_uid,omitempty"`
	ImapSeqNum    uint32                 `protobuf:"varint,5,opt,name=imap_seq_num,json=imapSeqNum,proto3" json:"imap_seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReceivedIMAP) Reset() {
	*x = EmailReceivedIMAP{}
	mi := &file_schema_email_received_imap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReceivedIMAP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReceivedIMAP) ProtoMessage() {}

func (x *EmailReceivedIMAP) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_received_imap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReceivedIMAP.ProtoReflect.Descriptor instead.
func (*EmailReceivedIMAP) Descriptor() ([]byte, []int) {
	return file_schema_email_received_imap_proto_rawDescGZIP(), []int{0}
}

func (x *EmailReceivedIMAP) GetInitialSync() bool {
	if x != nil {
		return x.InitialSync
	}
	return false
}

func (x *EmailReceivedIMAP) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *EmailReceivedIMAP) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *EmailReceivedIMAP) GetImapUid() uint32 {
	if x != nil {
		return x.ImapUid
	}
	return 0
}

func (x *EmailReceivedIMAP) GetImapSeqNum() uint32 {
	if x != nil {
		return x.ImapSeqNum
	}
	return 0
}

var File_schema_email_received_imap_proto protoreflect.FileDescriptor

const file_schema_email_received_imap_proto_rawDesc = "" +
	"\n" +
	" schema/email_received_imap.proto\x12\tmailstack\"\xaa\x01\n" +
	"\x11EmailReceivedIMAP\x12!\n" +
	"\finitial_sync\x18\x01 \x01(\bR\vinitialSync\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\x12\x19\n" +
	"\bimap_uid\x18\x04 \x01(\rR\aimapUid\x12 \n" +
	"\fimap_seq_num\x18\x05 \x01(\rR\n" +
	"imapSeqNumB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_received_imap_proto_rawDescOnce sync.Once
	file_schema_email_received_imap_proto_rawDescData []byte
)

func file_schema_email_received_imap_proto_rawDescGZIP() []byte {
	file_schema_email_received_imap_proto_rawDescOnce.Do(func() {
		file_schema_email_received_imap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_received_imap_proto_rawDesc), len(file_schema_email_received_imap_proto_rawDesc)))
	})
	return file_schema_email_received_imap_proto_rawDescData
}

var file_schema_email_received_imap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_email_received_imap_proto_goTypes = []any{
	(*EmailReceivedIMAP)(nil), // 0: mailstack.EmailReceivedIMAP
}
var file_schema_email_received_imap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_email_received_imap_proto_init() }
func file_schema_email_received_imap_proto_init() {
	if File_schema_email_received_imap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_received_imap_proto_rawDesc), len(file_schema_email_received_imap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_received_imap_proto_goTypes,
		DependencyIndexes: file_schema_email_received_imap_proto_depIdxs,
		MessageInfos:      file_schema_email_received_imap_proto_msgTypes,
	}.Build()
	File_schema_email_received_imap_proto = out.File
	file_schema_email_received_imap_proto_goTypes = nil
	file_schema_email_received_imap_proto_depIdxs = nil
}
