// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_analysis.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for email analysis
type AnalyzeEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmailId        string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	From           *EmailAddress          `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             []*EmailAddress        `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	EmailBodyText  string                 `protobuf:"bytes,4,opt,name=email_body_text,json=emailBodyText,proto3" json:"email_body_text,omitempty"`
	EmailBodyHtml  string                 `protobuf:"bytes,5,opt,name=email_body_html,json=emailBodyHtml,proto3" json:"email_body_html,omitempty"`
	MailboxId      string                 `protobuf:"bytes,6,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Classification EmailClassification    `protobuf:"varint,7,opt,name=classification,proto3,enum=mailstack.EmailClassification" json:"classification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeEmailRequest) Reset() {
	*x = AnalyzeEmailRequest{}
	mi := &file_schema_email_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeEmailRequest) ProtoMessage() {}

func (x *AnalyzeEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeEmailRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeEmailRequest) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeEmailRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *AnalyzeEmailRequest) GetFrom() *EmailAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *AnalyzeEmailRequest) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *AnalyzeEmailRequest) GetEmailBodyText() string {
	if x != nil {
		return x.EmailBodyText
	}
	return ""
}

func (x *AnalyzeEmailRequest) GetEmailBodyHtml() string {
	if x != nil {
		return x.EmailBodyHtml
	}
	return ""
}

func (x *AnalyzeEmailRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *AnalyzeEmailRequest) GetClassification() EmailClassification {
	if x != nil {
		return x.Classification
	}
	return EmailClassification_EMAIL_CLASSIFICATION_UNKNOWN
}

// Response message for email analysis
type AnalyzeEmailResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EmailId             string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	HasSignature        bool                   `protobuf:"varint,2,opt,name=has_signature,json=hasSignature,proto3" json:"has_signature,omitempty"`
	MessageBodyMarkdown string                 `protobuf:"bytes,3,opt,name=message_body_markdown,json=messageBodyMarkdown,proto3" json:"message_body_markdown,omitempty"`
	Signature           *EmailSignature        `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyzeEmailResponse) Reset() {
	*x = AnalyzeEmailResponse{}
	mi := &file_schema_email_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeEmailResponse) ProtoMessage() {}

func (x *AnalyzeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeEmailResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeEmailResponse) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeEmailResponse) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *AnalyzeEmailResponse) GetHasSignature() bool {
	if x != nil {
		return x.HasSignature
	}
	return false
}

func (x *AnalyzeEmailResponse) GetMessageBodyMarkdown() string {
	if x != nil {
		return x.MessageBodyMarkdown
	}
	return ""
}

func (x *AnalyzeEmailResponse) GetSignature() *EmailSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AnalyzeEmailResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// EmailSignature represents the complete email signature
type EmailSignature struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CompanyInfo   *EmailSignatureCompanyInfo `protobuf:"bytes,1,opt,name=company_info,json=companyInfo,proto3" json:"company_info,omitempty"`
	ContactInfo   *EmailSignatureContactInfo `protobuf:"bytes,2,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSignature) Reset() {
	*x = EmailSignature{}
	mi := &file_schema_email_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSignature) ProtoMessage() {}

func (x *EmailSignature) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSignature.ProtoReflect.Descriptor instead.
func (*EmailSignature) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *EmailSignature) GetCompanyInfo() *EmailSignatureCompanyInfo {
	if x != nil {
		return x.CompanyInfo
	}
	return nil
}

func (x *EmailSignature) GetContactInfo() *EmailSignatureContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

// EmailSignatureCompanyInfo contains company information
type EmailSignatureCompanyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *EmailSignatureAddress `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Github        string                 `protobuf:"bytes,3,opt,name=github,proto3" json:"github,omitempty"`
	Instagram     string                 `protobuf:"bytes,4,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Linkedin      string                 `protobuf:"bytes,5,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Twitter       string                 `protobuf:"bytes,6,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Website       string                 `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	Youtube       string                 `protobuf:"bytes,8,opt,name=youtube,proto3" json:"youtube,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSignatureCompanyInfo) Reset() {
	*x = EmailSignatureCompanyInfo{}
	mi := &file_schema_email_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSignatureCompanyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSignatureCompanyInfo) ProtoMessage() {}

func (x *EmailSignatureCompanyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSignatureCompanyInfo.ProtoReflect.Descriptor instead.
func (*EmailSignatureCompanyInfo) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *EmailSignatureCompanyInfo) GetAddress() *EmailSignatureAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *EmailSignatureCompanyInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *EmailSignatureCompanyInfo) GetYoutube() string {
	if x != nil {
		return x.Youtube
	}
	return ""
}

// EmailSignatureContactInfo contains the contact information of a person
type EmailSignatureContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CalendarLink  string                 `protobuf:"bytes,1,opt,name=calendar_link,json=calendarLink,proto3" json:"calendar_link,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Github        string                 `protobuf:"bytes,4,opt,name=github,proto3" json:"github,omitempty"`
	JobTitle      string                 `protobuf:"bytes,5,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Linkedin      string                 `protobuf:"bytes,6,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Mobile        string                 `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSignatureContactInfo) Reset() {
	*x = EmailSignatureContactInfo{}
	mi := &file_schema_email_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSignatureContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSignatureContactInfo) ProtoMessage() {}

func (x *EmailSignatureContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSignatureContactInfo.ProtoReflect.Descriptor instead.
func (*EmailSignatureContactInfo) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *EmailSignatureContactInfo) GetCalendarLink() string {
	if x != nil {
		return x.CalendarLink
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailSignatureContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// EmailSignatureAddress contains address information
type EmailSignatureAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Street        string                 `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSignatureAddress) Reset() {
	*x = EmailSignatureAddress{}
	mi := &file_schema_email_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSignatureAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSignatureAddress) ProtoMessage() {}

func (x *EmailSignatureAddress) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSignatureAddress.ProtoReflect.Descriptor instead.
func (*EmailSignatureAddress) Descriptor() ([]byte, []int) {
	return file_schema_email_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *EmailSignatureAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EmailSignatureAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EmailSignatureAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *EmailSignatureAddress) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EmailSignatureAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

var File_schema_email_analysis_proto protoreflect.FileDescriptor

const file_schema_email_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1bschema/email_analysis.proto\x12\tmailstack\x1a\x1aschema/email_address.proto\x1a&schema/email_classification_enum.proto\"\xbd\x02\n" +
	"\x13AnalyzeEmailRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12+\n" +
	"\x04from\x18\x02 \x01(\v2\x17.mailstack.EmailAddressR\x04from\x12'\n" +
	"\x02to\x18\x03 \x03(\v2\x17.mailstack.EmailAddressR\x02to\x12&\n" +
	"\x0femail_body_text\x18\x04 \x01(\tR\remailBodyText\x12&\n" +
	"\x0femail_body_html\x18\x05 \x01(\tR\remailBodyHtml\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x06 \x01(\tR\tmailboxId\x12F\n" +
	"\x0eclassification\x18\a \x01(\x0e2\x1e.mailstack.EmailClassificationR\x0eclassification\"\xe8\x01\n" +
	"\x14AnalyzeEmailResponse\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12#\n" +
	"\rhas_signature\x18\x02 \x01(\bR\fhasSignature\x122\n" +
	"\x15message_body_markdown\x18\x03 \x01(\tR\x13messageBodyMarkdown\x127\n" +
	"\tsignature\x18\x04 \x01(\v2\x19.mailstack.EmailSignatureR\tsignature\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xa2\x01\n" +
	"\x0eEmailSignature\x12G\n" +
	"\fcompany_info\x18\x01 \x01(\v2$.mailstack.EmailSignatureCompanyInfoR\vcompanyInfo\x12G\n" +
	"\fcontact_info\x18\x02 \x01(\v2$.mailstack.EmailSignatureContactInfoR\vcontactInfo\"\x8f\x02\n" +
	"\x19EmailSignatureCompanyInfo\x12:\n" +
	"\aaddress\x18\x01 \x01(\v2 .mailstack.EmailSignatureAddressR\aaddress\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06github\x18\x03 \x01(\tR\x06github\x12\x1c\n" +
	"\tinstagram\x18\x04 \x01(\tR\tinstagram\x12\x1a\n" +
	"\blinkedin\x18\x05 \x01(\tR\blinkedin\x12\x18\n" +
	"\atwitter\x18\x06 \x01(\tR\atwitter\x12\x18\n" +
	"\awebsite\x18\a \x01(\tR\awebsite\x12\x18\n" +
	"\ayoutube\x18\b \x01(\tR\ayoutube\"\x83\x02\n" +
	"\x19EmailSignatureContactInfo\x12#\n" +
	"\rcalendar_link\x18\x01 \x01(\tR\fcalendarLink\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06github\x18\x04 \x01(\tR\x06github\x12\x1b\n" +
	"\tjob_title\x18\x05 \x01(\tR\bjobTitle\x12\x1a\n" +
	"\blinkedin\x18\x06 \x01(\tR\blinkedin\x12\x16\n" +
	"\x06mobile\x18\a \x01(\tR\x06mobile\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\"\x96\x01\n" +
	"\x15EmailSignatureAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06street\x18\x05 \x01(\tR\x06streetB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_analysis_proto_rawDescOnce sync.Once
	file_schema_email_analysis_proto_rawDescData []byte
)

func file_schema_email_analysis_proto_rawDescGZIP() []byte {
	file_schema_email_analysis_proto_rawDescOnce.Do(func() {
		file_schema_email_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_analysis_proto_rawDesc), len(file_schema_email_analysis_proto_rawDesc)))
	})
	return file_schema_email_analysis_proto_rawDescData
}

var file_schema_email_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_schema_email_analysis_proto_goTypes = []any{
	(*AnalyzeEmailRequest)(nil),       // 0: mailstack.AnalyzeEmailRequest
	(*AnalyzeEmailResponse)(nil),      // 1: mailstack.AnalyzeEmailResponse
	(*EmailSignature)(nil),            // 2: mailstack.EmailSignature
	(*EmailSignatureCompanyInfo)(nil), // 3: mailstack.EmailSignatureCompanyInfo
	(*EmailSignatureContactInfo)(nil), // 4: mailstack.EmailSignatureContactInfo
	(*EmailSignatureAddress)(nil),     // 5: mailstack.EmailSignatureAddress
	(*EmailAddress)(nil),              // 6: mailstack.EmailAddress
	(EmailClassification)(0),          // 7: mailstack.EmailClassification
}
var file_schema_email_analysis_proto_depIdxs = []int32{
	6, // 0: mailstack.AnalyzeEmailRequest.from:type_name -> mailstack.EmailAddress
	6, // 1: mailstack.AnalyzeEmailRequest.to:type_name -> mailstack.EmailAddress
	7, // 2: mailstack.AnalyzeEmailRequest.classification:type_name -> mailstack.EmailClassification
	2, // 3: mailstack.AnalyzeEmailResponse.signature:type_name -> mailstack.EmailSignature
	3, // 4: mailstack.EmailSignature.company_info:type_name -> mailstack.EmailSignatureCompanyInfo
	4, // 5: mailstack.EmailSignature.contact_info:type_name -> mailstack.EmailSignatureContactInfo
	5, // 6: mailstack.EmailSignatureCompanyInfo.address:type_name -> mailstack.EmailSignatureAddress
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_schema_email_analysis_proto_init() }
func file_schema_email_analysis_proto_init() {
	if File_schema_email_analysis_proto != nil {
		return
	}
	file_schema_email_address_proto_init()
	file_schema_email_classification_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_analysis_proto_rawDesc), len(file_schema_email_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_analysis_proto_goTypes,
		DependencyIndexes: file_schema_email_analysis_proto_depIdxs,
		MessageInfos:      file_schema_email_analysis_proto_msgTypes,
	}.Build()
	File_schema_email_analysis_proto = out.File
	file_schema_email_analysis_proto_goTypes = nil
	file_schema_email_analysis_proto_depIdxs = nil
}
