// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/email_stored.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for a stored email notification
type EmailStored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	EmlKey        string                 `protobuf:"bytes,2,opt,name=eml_key,json=emlKey,proto3" json:"eml_key,omitempty"`
	MailboxId     string                 `protobuf:"bytes,3,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStored) Reset() {
	*x = EmailStored{}
	mi := &file_schema_email_stored_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStored) ProtoMessage() {}

func (x *EmailStored) ProtoReflect() protoreflect.Message {
	mi := &file_schema_email_stored_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStored.ProtoReflect.Descriptor instead.
func (*EmailStored) Descriptor() ([]byte, []int) {
	return file_schema_email_stored_proto_rawDescGZIP(), []int{0}
}

func (x *EmailStored) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *EmailStored) GetEmlKey() string {
	if x != nil {
		return x.EmlKey
	}
	return ""
}

func (x *EmailStored) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

var File_schema_email_stored_proto protoreflect.FileDescriptor

const file_schema_email_stored_proto_rawDesc = "" +
	"\n" +
	"\x19schema/email_stored.proto\x12\tmailstack\"`\n" +
	"\vEmailStored\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x17\n" +
	"\aeml_key\x18\x02 \x01(\tR\x06emlKey\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x03 \x01(\tR\tmailboxIdB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_email_stored_proto_rawDescOnce sync.Once
	file_schema_email_stored_proto_rawDescData []byte
)

func file_schema_email_stored_proto_rawDescGZIP() []byte {
	file_schema_email_stored_proto_rawDescOnce.Do(func() {
		file_schema_email_stored_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_email_stored_proto_rawDesc), len(file_schema_email_stored_proto_rawDesc)))
	})
	return file_schema_email_stored_proto_rawDescData
}

var file_schema_email_stored_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_email_stored_proto_goTypes = []any{
	(*EmailStored)(nil), // 0: mailstack.EmailStored
}
var file_schema_email_stored_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_email_stored_proto_init() }
func file_schema_email_stored_proto_init() {
	if File_schema_email_stored_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_email_stored_proto_rawDesc), len(file_schema_email_stored_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_email_stored_proto_goTypes,
		DependencyIndexes: file_schema_email_stored_proto_depIdxs,
		MessageInfos:      file_schema_email_stored_proto_msgTypes,
	}.Build()
	File_schema_email_stored_proto = out.File
	file_schema_email_stored_proto_goTypes = nil
	file_schema_email_stored_proto_depIdxs = nil
}
