// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/errors.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceName int32

const (
	ServiceName_SERVICE_UNKNOWN                  ServiceName = 0
	ServiceName_MAILSTACK_IMAP_SERVICE           ServiceName = 1
	ServiceName_MAILSTACK_STORAGE_SERVICE        ServiceName = 2
	ServiceName_MAILSTACK_CLASSIFICATION_SERVICE ServiceName = 3
	ServiceName_MAILSTACK_ANALYSIS_SERVICE       ServiceName = 4
	ServiceName_MAILSTACK_ATTACHMENT_SERVICE     ServiceName = 5
	ServiceName_MAILSTACK_THREADING_SERVICE      ServiceName = 6
	ServiceName_MAILSTACK_CONTENT_SERVICE        ServiceName = 7
	ServiceName_MAILSTACK_EVENT_LOGGER_SERVICE   ServiceName = 8
)

// Enum value maps for ServiceName.
var (
	ServiceName_name = map[int32]string{
		0: "SERVICE_UNKNOWN",
		1: "MAILSTACK_IMAP_SERVICE",
		2: "MAILSTACK_STORAGE_SERVICE",
		3: "MAILSTACK_CLASSIFICATION_SERVICE",
		4: "MAILSTACK_ANALYSIS_SERVICE",
		5: "MAILSTACK_ATTACHMENT_SERVICE",
		6: "MAILSTACK_THREADING_SERVICE",
		7: "MAILSTACK_CONTENT_SERVICE",
		8: "MAILSTACK_EVENT_LOGGER_SERVICE",
	}
	ServiceName_value = map[string]int32{
		"SERVICE_UNKNOWN":                  0,
		"MAILSTACK_IMAP_SERVICE":           1,
		"MAILSTACK_STORAGE_SERVICE":        2,
		"MAILSTACK_CLASSIFICATION_SERVICE": 3,
		"MAILSTACK_ANALYSIS_SERVICE":       4,
		"MAILSTACK_ATTACHMENT_SERVICE":     5,
		"MAILSTACK_THREADING_SERVICE":      6,
		"MAILSTACK_CONTENT_SERVICE":        7,
		"MAILSTACK_EVENT_LOGGER_SERVICE":   8,
	}
)

func (x ServiceName) Enum() *ServiceName {
	p := new(ServiceName)
	*p = x
	return p
}

func (x ServiceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceName) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_errors_proto_enumTypes[0].Descriptor()
}

func (ServiceName) Type() protoreflect.EnumType {
	return &file_schema_errors_proto_enumTypes[0]
}

func (x ServiceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceName.Descriptor instead.
func (ServiceName) EnumDescriptor() ([]byte, []int) {
	return file_schema_errors_proto_rawDescGZIP(), []int{0}
}

// ErrorEvent message for publishing error information
type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	EmailId       string                 `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RawData       []byte                 `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Publisher     ServiceName            `protobuf:"varint,6,opt,name=publisher,proto3,enum=mailstack.ServiceName" json:"publisher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_schema_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_schema_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ErrorEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ErrorEvent) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *ErrorEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorEvent) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *ErrorEvent) GetPublisher() ServiceName {
	if x != nil {
		return x.Publisher
	}
	return ServiceName_SERVICE_UNKNOWN
}

var File_schema_errors_proto protoreflect.FileDescriptor

const file_schema_errors_proto_rawDesc = "" +
	"\n" +
	"\x13schema/errors.proto\x12\tmailstack\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\n" +
	"ErrorEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x19\n" +
	"\bemail_id\x18\x03 \x01(\tR\aemailId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\braw_data\x18\x05 \x01(\fR\arawData\x124\n" +
	"\tpublisher\x18\x06 \x01(\x0e2\x16.mailstack.ServiceNameR\tpublisher*\xa9\x02\n" +
	"\vServiceName\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MAILSTACK_IMAP_SERVICE\x10\x01\x12\x1d\n" +
	"\x19MAILSTACK_STORAGE_SERVICE\x10\x02\x12$\n" +
	" MAILSTACK_CLASSIFICATION_SERVICE\x10\x03\x12\x1e\n" +
	"\x1aMAILSTACK_ANALYSIS_SERVICE\x10\x04\x12 \n" +
	"\x1cMAILSTACK_ATTACHMENT_SERVICE\x10\x05\x12\x1f\n" +
	"\x1bMAILSTACK_THREADING_SERVICE\x10\x06\x12\x1d\n" +
	"\x19MAILSTACK_CONTENT_SERVICE\x10\a\x12\"\n" +
	"\x1eMAILSTACK_EVENT_LOGGER_SERVICE\x10\bB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_errors_proto_rawDescOnce sync.Once
	file_schema_errors_proto_rawDescData []byte
)

func file_schema_errors_proto_rawDescGZIP() []byte {
	file_schema_errors_proto_rawDescOnce.Do(func() {
		file_schema_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_errors_proto_rawDesc), len(file_schema_errors_proto_rawDesc)))
	})
	return file_schema_errors_proto_rawDescData
}

var file_schema_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_errors_proto_goTypes = []any{
	(ServiceName)(0),              // 0: mailstack.ServiceName
	(*ErrorEvent)(nil),            // 1: mailstack.ErrorEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_schema_errors_proto_depIdxs = []int32{
	2, // 0: mailstack.ErrorEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: mailstack.ErrorEvent.publisher:type_name -> mailstack.ServiceName
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schema_errors_proto_init() }
func file_schema_errors_proto_init() {
	if File_schema_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_errors_proto_rawDesc), len(file_schema_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_errors_proto_goTypes,
		DependencyIndexes: file_schema_errors_proto_depIdxs,
		EnumInfos:         file_schema_errors_proto_enumTypes,
		MessageInfos:      file_schema_errors_proto_msgTypes,
	}.Build()
	File_schema_errors_proto = out.File
	file_schema_errors_proto_goTypes = nil
	file_schema_errors_proto_depIdxs = nil
}
