// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: schema/skip_inbound_processing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkipInboundProcessing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmailId        string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	MailboxId      string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Classification EmailClassification    `protobuf:"varint,3,opt,name=classification,proto3,enum=mailstack.EmailClassification" json:"classification,omitempty"`
	Details        string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkipInboundProcessing) Reset() {
	*x = SkipInboundProcessing{}
	mi := &file_schema_skip_inbound_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipInboundProcessing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipInboundProcessing) ProtoMessage() {}

func (x *SkipInboundProcessing) ProtoReflect() protoreflect.Message {
	mi := &file_schema_skip_inbound_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipInboundProcessing.ProtoReflect.Descriptor instead.
func (*SkipInboundProcessing) Descriptor() ([]byte, []int) {
	return file_schema_skip_inbound_processing_proto_rawDescGZIP(), []int{0}
}

func (x *SkipInboundProcessing) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *SkipInboundProcessing) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *SkipInboundProcessing) GetClassification() EmailClassification {
	if x != nil {
		return x.Classification
	}
	return EmailClassification_EMAIL_CLASSIFICATION_UNKNOWN
}

func (x *SkipInboundProcessing) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_schema_skip_inbound_processing_proto protoreflect.FileDescriptor

const file_schema_skip_inbound_processing_proto_rawDesc = "" +
	"\n" +
	"$schema/skip_inbound_processing.proto\x12\tmailstack\x1a&schema/email_classification_enum.proto\"\xb3\x01\n" +
	"\x15SkipInboundProcessing\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\tR\aemailId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12F\n" +
	"\x0eclassification\x18\x03 \x01(\x0e2\x1e.mailstack.EmailClassificationR\x0eclassification\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetailsB*Z(github.com/customeros/mailstack/proto/pbb\x06proto3"

var (
	file_schema_skip_inbound_processing_proto_rawDescOnce sync.Once
	file_schema_skip_inbound_processing_proto_rawDescData []byte
)

func file_schema_skip_inbound_processing_proto_rawDescGZIP() []byte {
	file_schema_skip_inbound_processing_proto_rawDescOnce.Do(func() {
		file_schema_skip_inbound_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_skip_inbound_processing_proto_rawDesc), len(file_schema_skip_inbound_processing_proto_rawDesc)))
	})
	return file_schema_skip_inbound_processing_proto_rawDescData
}

var file_schema_skip_inbound_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_skip_inbound_processing_proto_goTypes = []any{
	(*SkipInboundProcessing)(nil), // 0: mailstack.SkipInboundProcessing
	(EmailClassification)(0),      // 1: mailstack.EmailClassification
}
var file_schema_skip_inbound_processing_proto_depIdxs = []int32{
	1, // 0: mailstack.SkipInboundProcessing.classification:type_name -> mailstack.EmailClassification
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_skip_inbound_processing_proto_init() }
func file_schema_skip_inbound_processing_proto_init() {
	if File_schema_skip_inbound_processing_proto != nil {
		return
	}
	file_schema_email_classification_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_skip_inbound_processing_proto_rawDesc), len(file_schema_skip_inbound_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_skip_inbound_processing_proto_goTypes,
		DependencyIndexes: file_schema_skip_inbound_processing_proto_depIdxs,
		MessageInfos:      file_schema_skip_inbound_processing_proto_msgTypes,
	}.Build()
	File_schema_skip_inbound_processing_proto = out.File
	file_schema_skip_inbound_processing_proto_goTypes = nil
	file_schema_skip_inbound_processing_proto_depIdxs = nil
}
